/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appArriendos;

/**
 *
 * @author Phobos
 */

import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

public class frmClienteBusca extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmClienteBusca
     */
    public frmClienteBusca() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtrut = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/png32/tool-1.png"))); // NOI18N
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setName("jTable1"); // NOI18N
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTable1KeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("RUT");

        jLabel12.setText("EJ : (19293232-7)");

        txtrut.setName("txtrut"); // NOI18N
        txtrut.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtrutFocusLost(evt);
            }
        });
        txtrut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrutActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/png32/tool-1.png"))); // NOI18N
        jButton1.setText("BUSCAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/png32/tool.png"))); // NOI18N
        jButton4.setText("LIMPIAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtrut)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtrut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        //int row = jTable1.rowAtPoint( evt.getPoint());
        int fila = this.jTable1.getSelectedRow();

        // luego, obtengo la columna seleccionada

        int columna = this.jTable1.getSelectedColumn();

        // por ultimo, obtengo el valor de la celda

        String dato = String.valueOf(this.jTable1.getValueAt(fila, 0));
        ObtenerRegistro(dato);

    }//GEN-LAST:event_jTable1MouseClicked

          private void ObtenerRegistro(String rut){
        
        try
        {
             ResultSet rs, rs2 = null;
             Connection miConexion=(Connection) Conexion.GetConnection();
             Statement statement=(Statement) miConexion.createStatement();
             rs = statement.executeQuery("SELECT * from tb_cliente where rut = '"+ rut +"'");
             
             while(rs.next()){
                 
                 frmReservaEquipo.txtRut.setText(rs.getString("rut"));
                 frmReservaEquipo.txtNombre.setText(rs.getString("nombre"));
                 frmReservaEquipo.txtTelefono.setText(rs.getString("telefono"));
                 frmReservaEquipo.txtCelular.setText(rs.getString("celular"));
                 frmReservaEquipo.txtEmail.setText(rs.getString("email"));
                     
                 this.dispose();
             }
             
             miConexion.close();
        }
        catch (Exception ex)
        {
            //JOptionPane.showMessageDialog(this, "Error "+ex.getMessage());
        }

    }
    
    
    private void jTable1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1KeyTyped

    private void txtrutFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtrutFocusLost
        // TODO add your handling code here:

        if(! txtrut.getText().trim().isEmpty())
        {

            if(! txtrut.getText().contains("-")){
                JOptionPane.showMessageDialog(this, "Rut formato incorrecto \n Ejemplo : 19293232-7");
            }
            else
            {
                if ( txtrut.getText().length() > 0  )
                {
                    // Creamos un arreglo con el rut y el digito verificador
                    String[] rut_dv = txtrut.getText().split("-");
                    // Las partes del rut (numero y dv) deben tener una longitud positiva
                    if ( rut_dv.length == 2   )
                    {
                        // Capturamos error (al convertir un string a entero)
                        try
                        {
                            int rut = Integer.parseInt( rut_dv[0] );
                            char dv = rut_dv[1].charAt(0);

                            // Validamos que sea un rut valido según la norma
                            if ( this.ValidarRut(rut, dv)  )
                            {
                                JOptionPane.showMessageDialog(rootPane, "Rut correcto");
                            }
                            else
                            {
                                JOptionPane.showMessageDialog(rootPane, "Rut incorrecto");
                            }
                        }
                        catch( Exception ex )
                        {
                            System.out.println(" Error " + ex.getMessage());
                        }
                    }
                }
            }

        }

    }//GEN-LAST:event_txtrutFocusLost

    private void txtrutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrutActionPerformed
        // TODO add your handling code here:

        if(! txtrut.getText().trim().isEmpty())
        {

            if(! txtrut.getText().contains("-")){
                JOptionPane.showMessageDialog(this, "Rut formato incorrecto \n Ejemplo : 19293232-7");
            }
            else
            {
                if ( txtrut.getText().length() > 0  )
                {
                    // Creamos un arreglo con el rut y el digito verificador
                    String[] rut_dv = txtrut.getText().split("-");
                    // Las partes del rut (numero y dv) deben tener una longitud positiva
                    if ( rut_dv.length == 2   )
                    {
                        // Capturamos error (al convertir un string a entero)
                        try
                        {
                            int rut = Integer.parseInt( rut_dv[0] );
                            char dv = rut_dv[1].charAt(0);

                            // Validamos que sea un rut valido según la norma
                            if ( this.ValidarRut(rut, dv)  )
                            {
                                JOptionPane.showMessageDialog(rootPane, "Rut correcto");
                            }
                            else
                            {
                                JOptionPane.showMessageDialog(rootPane, "Rut incorrecto");
                            }
                        }
                        catch( Exception ex )
                        {
                            System.out.println(" Error " + ex.getMessage());
                        }
                    }
                }
            }

        }

    }//GEN-LAST:event_txtrutActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
         Listar();
    }//GEN-LAST:event_formInternalFrameOpened

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         txtrut.setText("");
         Listar();
    }//GEN-LAST:event_jButton4ActionPerformed
//boton Busqueda jbutton1
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
  
        Connection miConexion=(Connection) Conexion.GetConnection();
        try
        {
            if(txtrut.getText().trim().isEmpty())
            {
               JOptionPane.showMessageDialog(this, "Debe ingresar campo rut"); 
            }
            else
            {
 
                 Statement statement=(Statement) miConexion.createStatement();
                 String rut = txtrut.getText();
            
                 ResultSet rs = statement.executeQuery("SELECT COUNT(*) AS num FROM tb_cliente WHERE rut LIKE '%"+ rut +"%' ");
                 int rows= 0;
                 if(rs.next()){
                     rows = rs.getInt("num");
                 }
            
                 if(rows > 0)
                 {                
                     DefaultTableModel modelo = new DefaultTableModel(); jTable1.setModel(modelo);
                     rs = statement.executeQuery("SELECT * FROM tb_cliente WHERE rut LIKE '%"+ rut +"%' ");
 
                     modelo.addColumn("RUT");
                     modelo.addColumn("NOMBRE");
                     modelo.addColumn("DIRECCION");
                     while(rs.next()){
                         Object []ob=new Object[4];
                         ob[0]=(rs.getString("rut"));
                         ob[1]=(rs.getString("nombre"));
                         ob[2]=(rs.getString("direccion"));
                         modelo.addRow(ob);
                         ob=null;
                     }                                                                
                     statement.close();
                     miConexion.close();    
                 }
                 else
                 {           
                     JOptionPane.showMessageDialog(this, "Rut de cliente ingresado existente en sistema");          
                 }
                
            }

        }
        catch (Exception ex)
        {
            JOptionPane.showMessageDialog(this, "Error "+ex.getMessage());
        }       
        
    }//GEN-LAST:event_jButton1ActionPerformed

    
    public static boolean ValidarRut(int rut, char dv)
    {
        int m = 0, s = 1;
        for (; rut != 0; rut /= 10)
        {
            s = (s + rut % 10 * (9 - m++ % 6)) % 11;
        }
        return dv == (char) (s != 0 ? s + 47 : 75);
    }

    public  void Listar(){
        DefaultTableModel modelo = 
         new DefaultTableModel();
 jTable1.setModel(modelo);
 
        try
        {        
        ResultSet rs = null;
        Connection miConexion=(Connection) Conexion.GetConnection();
        Statement statement=(Statement) miConexion.createStatement();
        
         rs = statement.executeQuery("SELECT * from tb_cliente");
 
         modelo.addColumn("RUT");
         modelo.addColumn("NOMBRE");
         modelo.addColumn("DIRECCION");
         while(rs.next()){
            Object []ob=new Object[4];
            ob[0]=(rs.getString("rut"));
            ob[1]=(rs.getString("nombre"));
            ob[2]=(rs.getString("direccion"));
            modelo.addRow(ob);
            ob=null;
         }    
            rs.close();
            statement.close();
            miConexion.close();
            
        }
        catch (Exception ex)
        {
            JOptionPane.showMessageDialog(this, "Error "+ex.getMessage());
        }
    }  
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtrut;
    // End of variables declaration//GEN-END:variables
}
